# -*- coding: utf-8 -*-
"""Bases de datos y visualizacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xz6OyaA3n5bKqNSi6Ag9vk2ilGyCY5ZQ
"""



"""# Introducción a la Innovación Disruptiva

## Creación de bases de datos

![Image](https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExdmd6cWVvdmFuZzNramhibmc0dTg0NnF1NHhlMzV2Y3B1M2Juc3JneiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3ohzdMk3uz9WSpdTvW/giphy.gif)


"""

Top_startups =[
  {
    "name": "ByteDance",
    "valuation": "$225B",
    "description": "Conocida por TikTok y su enfoque en inteligencia artificial.",
    "url": "https://www.brandvm.com/post/10-highest-valued-startups-2024?utm_source=chatgpt.com"
  },
  {
    "name": "SpaceX",
    "valuation": "$150B",
    "description": "Líder en la industria aeroespacial con cohetes reutilizables y la red satelital Starlink.",
    "url": "https://www.brandvm.com/post/10-highest-valued-startups-2024?utm_source=chatgpt.com"
  },
  {
    "name": "Lynksoul",
    "valuation": "N/A",
    "description": "Desarrolla compañeros virtuales impulsados por IA para videojuegos y películas.",
    "url": "https://www.theinformation.com/projects/the-information-50-2024?utm_source=chatgpt.com"
  },
  {
    "name": "Pixxel",
    "valuation": "N/A",
    "description": "Empresa de satélites de imágenes hiperespectrales con contratos de la NASA.",
    "url": "https://en.wikipedia.org/wiki/Pixxel?utm_source=chatgpt.com"
  },
  {
    "name": "Neysa",
    "valuation": "N/A",
    "description": "Plataforma de infraestructura en la nube con IA generativa.",
    "url": "https://en.wikipedia.org/wiki/Neysa?utm_source=chatgpt.com"
  },
  {
    "name": "Perplexity AI",
    "valuation": "$9B",
    "description": "Motor de búsqueda conversacional basado en IA con 10 millones de usuarios activos mensuales.",
    "url": "https://www.codeconcepts.tech/blog/fast-growing-companies?utm_source=chatgpt.com"
  },
  {
    "name": "xAI",
    "valuation": "$24B",
    "description": "Fundada por Elon Musk, especializada en IA multimodal con su modelo Grok.",
    "url": "https://digitalworldz.com/business/the-top-23-startups-of-2024-the-new-titans-of-tech-406/?utm_source=chatgpt.com"
  },
  {
    "name": "OpenAI",
    "valuation": "$157B",
    "description": "Líder en IA generativa, recaudó $6.6 mil millones en 2024.",
    "url": "https://www.reuters.com/technology/artificial-intelligence/ai-startups-ride-investor-frenzy-raise-billions-2024-2024-10-04/?utm_source=chatgpt.com"
  },
  {
    "name": "Scale AI",
    "valuation": "$13.8B",
    "description": "Plataforma que facilita el desarrollo de aplicaciones de IA mediante datos etiquetados.",
    "url": "https://forgeglobal.com/insights/startup-trends-4-top-funded-startups-q2-2024/?utm_source=chatgpt.com"
  },
  {
    "name": "Formation Bio",
    "valuation": "N/A",
    "description": "Startup farmacéutica que utiliza IA para acelerar el desarrollo de tratamientos.",
    "url": "https://forgeglobal.com/insights/startup-trends-4-top-funded-startups-q2-2024/?utm_source=chatgpt.com"
  }
]

EID_701 = {"Rodrigo":[21, "soltero", "Valeria",1.70],
       "Sam": [21, "soltera", "Blee", 1.67],
       "Luis": [20, "soltero", "Angie", 1.65]}

EID_701.keys()

EID_701.values()

import pandas as pd

DF_701 = pd.DataFrame(EID_701)

DF_701

# ¿Cuáles son los datos de Sam?
DF_701["Sam"]

# ¿Cuáles ses la edad de Sam?
DF_701["Sam"][0]

Top_startups[2]

pd.DataFrame(Top_startups)

"""#Bases de datos"""

estudiantes={"Sam": [3,4,5.9,8,3.3],
             "Angel":[-1.5,0,2,5,10],
             "Rangel":[7.7,8.0,8.2,9,9],
             "Zarate":[0,10,8,3.5,0],
             "Rica":[3,6.2,7,2,8]}

import pandas as pd
tablita=pd.DataFrame(estudiantes)
tablita

tablita.describe()

import seaborn as sns

sns.boxplot(data=tablita)

import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

fig = px.box(tablita,
             title="📊 Distribución de Calificaciones por Estudiante",
             labels={"value": "Calificación", "variable": "Estudiante"})

# Personalizar el gráfico
fig.update_layout(
    template="plotly_white",
    font=dict(size=12),
    hovermode="x unified",
    height=600,
    width=800
)

fig.update_traces(boxpoints='all', jitter=0.3, pointpos=-1.8)  # Mostrar todos los puntos

# Mostrar el gráfico
fig.show()