# -*- coding: utf-8 -*-
"""Clase2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/130h_YVG5tfs4C2oo1C9oC0gD5JNnfhx5
"""

import pandas as pd

ch=pd.read_csv("california_housing_test.csv")
ch.head() #va a mostrar la tabla con los primeros 5 renglones

from google.colab import drive
drive.mount('/content/drive')

ch.describe()

ch_1 = ch[["total_rooms","population","median_income","median_house_value"]]
ch_1["median_income"]

"""# Visualizacion de datos"""

import seaborn as sns
import matplotlib.pyplot as plt

# Melt the DataFrame to long format for easier plotting of multiple columns
ch_melted = ch.melt()

# Create the boxplot
plt.figure(figsize=(12, 6)) # Adjust figure size for better readability
sns.boxplot(x='variable', y='value', data=ch_melted)
plt.title('Boxplot of California Housing Data')
plt.xticks(rotation=45) # Rotate x-axis labels for better readability
plt.tight_layout() # Adjust layout to prevent labels overlapping
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))
sns.boxplot(y=ch['median_house_value'])
plt.title('Boxplot of Median House Value')
plt.ylabel('Median House Value')
plt.show()

ch_1

ch_1["median_house_value"]<= 30000.0

ch_1[ch_1["median_house_value"]<= 30000.0]

filtered_ch_1.describe()

filtered_ch_1.info

filtered_ch_1.iloc[5]

filtered_ch_1 = filtered_ch_1.reset_index(drop=True)
display(filtered_ch_1.head())